# Repository
repo_name: 'awslabs/iam-roles-anywhere-session'
repo_url: 'https://github.com/awslabs/iam-roles-anywhere-session'

site_name: IAM Roles Anywhere Session
theme:
  name: 'material'
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.sections

markdown_extensions:
  - footnotes
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
  - attr_list


plugins:
  - mkdocstrings
  - search
  - autorefs
